jobname: esm-pmip-lm
queue: normal
walltime: 1:45:00

# note: if laboratory is relative path, it is relative to /scratch/$PROJECT/$USER
laboratory: access-esm
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 20
      exe: /scratch/w35/hxw599/access-esm/pmip-lm/build/bin/um_hg3.exe
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/atmosphere
        - /g/data/access/payu/access-esm/input/pmip-lm/atmosphere

    - name: ocean
      model: mom
      ncpus: 16
      exe: /g/data/access/payu/access-esm-pmip/pmip-mh/bin/mom5xx
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/common
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: /g/data/access/payu/access-esm-pmip/pmip-mh/bin/cicexx
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/coupler

collate:
   exe: /g/data/access/payu/access-esm/bin/mppnccombine
   restart: true
   mem: 4GB

mpi:
    runcmd: ddt --connect mpirun
modules:
    - arm-forge

restart: /g/data/access/payu/access-esm/restart/pmip-lm

calendar:
    start:
        year: 850
        month: 1
        days: 1

    runtime:
        years: 1 # NOTE: Must be 1 year for land use updates
        months: 0
        days: 0

userscripts:
    init: # ./scripts/set_restart_year.sh 850 # For spinup - reset the year to 0850
    run: ./update_landuse.py # Update land use after the run

runspersub: 1

stacksize: unlimited

qsub_flags: -W umask=027 -l jobfs=100gb
