format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /scratch/w35/saw562/access-esm/holger-build/pmip-lm/build/bin/um_hg3.exe
  hashes:
    binhash: f25c21d35df004a49015c51b3b45867a
    md5: f783825a95c95ca1dc30c76a592a5373
work/ice/cicexx:
  fullpath: /g/data/access/payu/access-esm-pmip/pmip-mh/bin/cicexx
  hashes:
    binhash: 018e0dcf4b20fd68146886dc603f2494
    md5: f0b4fd30e8c6a610b3b38acc21bb7f7f
work/ocean/mom5xx:
  fullpath: /g/data/access/payu/access-esm-pmip/pmip-mh/bin/mom5xx
  hashes:
    binhash: d0fb87c8a100bcc7d7c77f748e7795b1
    md5: 0379a87d865b45ea7d8cbc1fb53c9d5e
