format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/atmosphere/restart_dump.astart
  hashes:
    binhash: feb4655f0643f2f5a76f7efd44c48abf
    md5: de372baa2c91f9a8467ec5cb3434c8d9
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/atmosphere/um.res.yaml
  hashes:
    binhash: 7069b291d6e8a75fc27891ca7f43f3bc
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/coupler/a2i.nc
  hashes:
    binhash: 841a3a05c24f9a844e2ec1a2e867eb79
    md5: 16fd2f2b57dd75134ea687285f569191
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/coupler/i2a.nc
  hashes:
    binhash: 9e8162866f55857c86c6d3161806dc1c
    md5: 69689614b979601214b863a6455a02d4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/coupler/o2i.nc
  hashes:
    binhash: 0c3972707d884c45f9d61882c5787142
    md5: c6337cddd366ac385b7d21f4555c0cb3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/cice_in.nml
  hashes:
    binhash: ee88ae8c3fc7f62f2b8f07341bf0861e
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/ice.restart_file
  hashes:
    binhash: 91e10636810253af3d40d593ef06c784
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.13940101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940101
  hashes:
    binhash: 488934603f20a35c59322337448cc0ea
    md5: 73f47b91b5e989a1e91851775f46a34c
work/ice/RESTART/iced.13940201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940201
  hashes:
    binhash: 774d57052a09add83d24de3cc4b0ad5f
    md5: 4935a8a1554500846b4d7c8ca3ee4fc3
work/ice/RESTART/iced.13940301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940301
  hashes:
    binhash: a6acf754b534191278b1601129090f97
    md5: 0833902776f4f69ab6604facad4a3ec0
work/ice/RESTART/iced.13940401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940401
  hashes:
    binhash: c1773fd64195c244b815202a5d2fa9d3
    md5: cdde12610a9ec6903e5ce7d2a9e83dc6
work/ice/RESTART/iced.13940501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940501
  hashes:
    binhash: d6dc52bb909009b0dc7418d6bba04b01
    md5: 414d1351b1e19cbca23e4593c8ea5f5f
work/ice/RESTART/iced.13940601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940601
  hashes:
    binhash: c60547db570b05c9050865b983d0a541
    md5: 0f35771e408081ed3d036c63799e011c
work/ice/RESTART/iced.13940701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940701
  hashes:
    binhash: 9e79fec5e16001e37540bead4e41271f
    md5: b7fe10e5b3b3c851570beb9d643976d9
work/ice/RESTART/iced.13940801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940801
  hashes:
    binhash: 918b98b077a2f40a08453e8a3b221a4e
    md5: 0f322b00e7257efbfdc511f6fc3b33d3
work/ice/RESTART/iced.13940901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13940901
  hashes:
    binhash: 4954c3399af7dfc5bb086cc46da572ec
    md5: cbfa490a818418d11a9cfc049b27e707
work/ice/RESTART/iced.13941001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13941001
  hashes:
    binhash: e6f6134e71a1664ef590e5cc9401d489
    md5: 314e8019438b2689d2dd66c3fe99177a
work/ice/RESTART/iced.13941101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13941101
  hashes:
    binhash: dc6361ed6754689a56fbdfc41a6ed9dc
    md5: 23d76ef8b086418ec7941e9b626adaab
work/ice/RESTART/iced.13941201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/iced.13941201
  hashes:
    binhash: ea2ea7ec4a0372c9bba0de53eb4a1320
    md5: af5aadcb4447867fd91d9ad8c93b6951
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/input_ice.nml
  hashes:
    binhash: 70aded3d78b4c35cf7b7cc7a3545c1d2
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/mice.nc
  hashes:
    binhash: 0b87a6e08c8ba14fe53ae03e756c824d
    md5: c22882b047ae45c13ae930aefbd965b8
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ice/reset.iced.850
  hashes:
    binhash: 0d3aea0fdd875b7626a365c428fff6d5
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 8c658e150372e48ca9776fc1872a184d
    md5: ab7c003ab65c7840154ce7acbcf9de73
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: d3935066b007ffefc0282e7c05420b5d
    md5: 8e64d66b8daa6ac791be53041d6268e5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_age.res.nc
  hashes:
    binhash: c2a1b6bd7657a2dddc0b2184173aca81
    md5: 271a72a358e2bb52b322354631fe1ea3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2040188161a3f632ad9bdc139e313f38
    md5: b15c3f8e8c0291cc249ca97724b30d5d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dcdcbb497b0e1b900e69ae431f5ee6b1
    md5: 150f009e5192c937df2d6d6c1c26d601
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_density.res.nc
  hashes:
    binhash: ce8395aebc0a27eb8651f7f3e27b20d4
    md5: c6219dfaaf53f4b75b7beb9bfa8e1822
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cce3bbaba4278477714d5cafcc862fd7
    md5: 4c4a821feb17dfba69358b0e6daf6de6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6f589abf7467d1d0bac5b08743e915a9
    md5: f7302b196c646ab52021a803049863bd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c72ea6869e1466a9139d9450c2312e75
    md5: e739a8fa1d2a3e17d827d58f6895958d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 81565477788ee118d108977ff4e3c6d8
    md5: 5092f77efcfb2041ed42ea728e24b8f3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6925576928bf2604f90c0db62faee7b6
    md5: 835f6cdd83683f15018938156fbd9570
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 22397d2a70f104d16c03207736681e33
    md5: 9dc480316d10000c4e5c5bf7c938bc62
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_solo.res
  hashes:
    binhash: 36a8c5abf03babadf9f30cb89003bce3
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 71e05d353a134a32934d6db431e69829
    md5: 278737836f1cfc64be14b56a74013ea5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2fc16c63e4233d5678200559c33fcd9f
    md5: 776c236c85d0a62a95855fa267b7ec50
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_tracer.res
  hashes:
    binhash: 4ddbf82cb5493362e682cbe711410bcb
    md5: e11c082af3dcf4bff940da8e7360b1a2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7358c9051882ea8405852b14199db41a
    md5: a54e125838aceb267111378b2ff481f8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart005/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 601dee238c17469cc3ffd61f9d167c13
    md5: e2a987dc6f506b4d973f3cf5b8d3a19b
