format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/atmosphere/restart_dump.astart
  hashes:
    binhash: eabd28acb9772ff5757b89e2a0d71052
    md5: 78a1e5c34729a1a20148c4fe13f3b63e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/atmosphere/um.res.yaml
  hashes:
    binhash: 053ba2f83b2c7c7189e3bcfd0a482f25
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/coupler/a2i.nc
  hashes:
    binhash: f8e3e900c16a3571aeee91957971bab6
    md5: 64486979b65bd48e164e21d23f2a03e7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/coupler/i2a.nc
  hashes:
    binhash: da6faa705f77015fa862a35b2634fab0
    md5: 68398e24344969cc15f9e3a667cd50f2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/coupler/o2i.nc
  hashes:
    binhash: 394e98b29bf8e1092f2edf4bd8d6228f
    md5: d0ecd0c89ac3000b70c69936faf68dc9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/cice_in.nml
  hashes:
    binhash: bb169dcb36cf03c490e171e1fad1776a
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/ice.restart_file
  hashes:
    binhash: 909da47286f8ea133ff277be8b971421
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.14491101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14491101
  hashes:
    binhash: d8eaaa8c2ecf8bbc943f86559f6dd21d
    md5: a790049645b60abf8c82b449220cd34e
work/ice/RESTART/iced.14491201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14491201
  hashes:
    binhash: c845a543aacd8befdb16c596de8a44ae
    md5: 95f8bd6155a9c1aa24b6232d6f289e21
work/ice/RESTART/iced.14500101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500101
  hashes:
    binhash: d0d6c294c75efbbcfc9686d5306f353c
    md5: 62acadc08dca8b3a5370c42c1aa57da9
work/ice/RESTART/iced.14500201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500201
  hashes:
    binhash: 6db8a11da5df059b747f54f5716d6551
    md5: f53300cbc8cc93cc681cde7f24ba8c3f
work/ice/RESTART/iced.14500301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500301
  hashes:
    binhash: 433cc45a5ab8f9385f0375b1259c5605
    md5: c3983eb9342f46edc4417f8b8bdd296c
work/ice/RESTART/iced.14500401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500401
  hashes:
    binhash: 57579df4b491689d97d15d5504a50f52
    md5: dcc8c45b3b034298e2153dbe74cfce7d
work/ice/RESTART/iced.14500501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500501
  hashes:
    binhash: f928e668e90f2a4dd3a3f1ba01d53e25
    md5: f15dc2244b68eb5d70a017610d0c8ba1
work/ice/RESTART/iced.14500601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500601
  hashes:
    binhash: 3454b04871f3de765518151b3b854f51
    md5: cf3e8e4b4b9e7e78b82a08083dd2eff7
work/ice/RESTART/iced.14500701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500701
  hashes:
    binhash: 2fd5b0e0db76beddac0b8496884719d7
    md5: 9980392fcf1d8d351963726ebafefb89
work/ice/RESTART/iced.14500801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500801
  hashes:
    binhash: f83796bf2311e64a860a5a0dce214cea
    md5: 5436c1ebb62ba4505276d92f13eb6834
work/ice/RESTART/iced.14500901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14500901
  hashes:
    binhash: ddb876a4bd76421bae9099785e6ddb00
    md5: 2e3ac08d51c3450354cb04eb845bed9e
work/ice/RESTART/iced.14501001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/iced.14501001
  hashes:
    binhash: 20b4012a967e7de6d3cffa7063e14dd1
    md5: c46610af3e07343b24d491f281295176
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/input_ice.nml
  hashes:
    binhash: 680698d5964420d91c2c2b388493b5b5
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/mice.nc
  hashes:
    binhash: a82cd7ec2f20d5a643c06ea54d323549
    md5: 7830d5e08165e642255defd1ca7b85a9
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ice/reset.iced.850
  hashes:
    binhash: d476667498bc6b0e65e28f0760878765
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/csiro_bgc.res.nc
  hashes:
    binhash: b5dac86293ec459252c62962e4dd7858
    md5: bbc2fca2f017c588174d24ac73fe14d0
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: e5fcf2b91978afe7dcde900b9309a3b4
    md5: 2ffe7208ab9d00a73485beef5f166b5a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_age.res.nc
  hashes:
    binhash: c169dc33e0850c2bd8f91603a84a2251
    md5: e25320912a6209625f0daced64777430
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5adcf34dc1122936020c07d22d958c8f
    md5: dcf93fcd6863698a712e0916de965db1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6710e788e7c66f787e58a9e4ef98efec
    md5: 2b36aff88b1a58702a07bcd70a511f32
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_density.res.nc
  hashes:
    binhash: 275519fe3a8ad1d3866a5b6146014d1e
    md5: d89ea04cd6dceac0f71e8fa1cfa8347e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d290df0e3ba906e74057acf50c7c0623
    md5: 8d283f3d521191e1e9e5a550cebaf539
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9a4c8a222fd059a09f9b948b089a6d2f
    md5: 9e6613a4f85d8bbe5d5df46e4c05e16c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a88844a69a7b4a0e973f4e515f9edbb9
    md5: 3cc58e80cbbc10f5b68177056b883ebd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 33c744da3c8ce4684082f96f30e98637
    md5: c73309268673031f404600b3be0967a6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4b2a1013181aa70f348f82f80028f472
    md5: a3d188eb35c36e0e2d22eec6c1ded635
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 37d35df5033bb1bdb2bb77c27fef2e1a
    md5: 9dc480316d10000c4e5c5bf7c938bc62
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_solo.res
  hashes:
    binhash: a891cd876a5f90e53d05ee7ec5998e6d
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a6d4f734481cdef188022b293b1c6231
    md5: 14192a53244ca58a90bbe8cb53679d79
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 141ede130f09e11b998d0cd8c4ff4f66
    md5: 929e642eb46a32a47ab3438f3665e513
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_tracer.res
  hashes:
    binhash: 7668dda66db15596200d169b2b9b4dfd
    md5: 3b2361bd73b302b0fa9c525dc3f4c279
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dde32a71d513f0903027e6c1b012ffbd
    md5: 7cfcf5b2960c00378a57b237abd87d3a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart062/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e248c347e0e7495005f822bb669117f2
    md5: f627d8756d7b005c023b63ab24f5a334
