format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/atmosphere/restart_dump.astart
  hashes:
    binhash: 9e2123d592fc12cc502fe684576e591f
    md5: 68948882d244d2ddad9535413e12c47b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/atmosphere/um.res.yaml
  hashes:
    binhash: 0d9f5426088e4ea4d3059345a989373f
    md5: e785058bad1cd1704b4058f4052c6565
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/coupler/a2i.nc
  hashes:
    binhash: 9ae1786984e60cd9d178c388e87f9cf1
    md5: f199f788e74787630369fd549ac8c651
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/coupler/i2a.nc
  hashes:
    binhash: 9e428ea32e136fb4aca2d8b4115fd245
    md5: 249cf393774d7b91d2b30e8055c3ec8e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/coupler/o2i.nc
  hashes:
    binhash: bf30274bf4a689e1a8822185ee2adbb8
    md5: 6adb6858fcd381b46029e44d44253738
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/cice_in.nml
  hashes:
    binhash: 99e90508a44c6ee4cbd32f3bc7533079
    md5: 167ce626f087671968b5f76d2aea3a6c
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/ice.restart_file
  hashes:
    binhash: e6418c99c790ba8256ab789b4c169d48
    md5: 761dc0cdcb3a9a2177d2d039f35323bc
work/ice/RESTART/iced.19770401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19770401
  hashes:
    binhash: d956fcd189379da5491607c7305c03ad
    md5: 2ea3554201fcb6447f01468fecdecbf0
work/ice/RESTART/iced.19770501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19770501
  hashes:
    binhash: 9c1987b7c276cf71313792acc1e2c940
    md5: d7ba69dfc7cdb752b7d6058f44b33bfe
work/ice/RESTART/iced.19770601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19770601
  hashes:
    binhash: 9a45e327d39532ae98d59b822075be61
    md5: 1baeeaac850bc7e046c94c2bcb108e7a
work/ice/RESTART/iced.19770701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19770701
  hashes:
    binhash: 93d4e079df52586c85ebf0c908888e61
    md5: 1a403aee964fa9291a0ae96c610b09a7
work/ice/RESTART/iced.19770801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19770801
  hashes:
    binhash: e8ebb45331d869cb2c3f042c956da60d
    md5: 05e301d82d0e9471b172b9257168834d
work/ice/RESTART/iced.19770901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19770901
  hashes:
    binhash: ba161aa3dcb505206f239e2a58e23435
    md5: 117ce48aaf9b661dfefd4c0075234a71
work/ice/RESTART/iced.19771001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19771001
  hashes:
    binhash: 89e73de44f2b3ed8adab4bcbc6cd006b
    md5: 319f6737cc3b7c1fb24dfe93622bd9e0
work/ice/RESTART/iced.19771101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19771101
  hashes:
    binhash: b3b20393a388629b6653146364aca2c4
    md5: e415ef33b72d953bd678040bc7c5049c
work/ice/RESTART/iced.19771201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19771201
  hashes:
    binhash: 0043bb27a68aad8e249b4421b61be7df
    md5: 5d126dfc8423763f6640d4f66de2daf9
work/ice/RESTART/iced.19780101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19780101
  hashes:
    binhash: be11d597c408a534887c8dbc49dbbaf2
    md5: 67f8e31e863e3e622a6f88e89a9b7dad
work/ice/RESTART/iced.19780201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19780201
  hashes:
    binhash: 0f0e46cea8ac4781d459beb867f41d9a
    md5: 962aa8334165c1b1506b934781234761
work/ice/RESTART/iced.19780301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/iced.19780301
  hashes:
    binhash: efa6e2910ba6e8065bac14893f731910
    md5: b24397c494db59de40e17477b2b39bae
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/input_ice.nml
  hashes:
    binhash: 5e007ce0dedfdcab6d951ce89b2166bd
    md5: 62e3fa9477ba491d8fb485d62723cedc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/mice.nc
  hashes:
    binhash: 3a19afcf3db21b4100e4aaed372547a6
    md5: 6b1777d5085b040e96633f13e9a50ca6
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ice/reset.iced.850
  hashes:
    binhash: 9a574f209e187b83fc71b2034b57514a
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 94b79e3bfbfcc3193cdadeb06dd1c852
    md5: 7cd16c9b00935f61c9602f725ebf92f3
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: edd9f5c24202d8d215f7d2a68823b9fd
    md5: 9cfab7a6e81c7cd9598a56738d6ad441
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_age.res.nc
  hashes:
    binhash: 14451289a804fd5cbee0041a22f1d2e2
    md5: 2fb0899083d19a3ef1f9d307e0c4df93
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8befdde819f258d2a439ec768808e31f
    md5: fb7313f71954b8648e1bf89af106b01f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bc95c2b49f9915417c1c5b5594ee75db
    md5: e9f1b4bec4bfb3a022bb461bede10e24
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_density.res.nc
  hashes:
    binhash: 5d7813e1ea029083e6e7c9a643d874c5
    md5: efde44212de24f74ee55c8df11cc471d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bfca73b704238bc5b35fe849d9e27e31
    md5: 80c9e255d88d5c2c79339814e1c0a64e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 63c068bb5c60b2792edb07ef0e0c8c43
    md5: 22c3fd8326a297d4b4d6eef11f8eb4a2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7b5fc96685af795a6963a2024cf769cb
    md5: 3aff3db2cef856379aee511101391d85
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 262b5679ea0f24bc301f561c2d532fbc
    md5: 57869e677f46506334cfd9ec64f5b311
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 967839cb66fbb9ad511250e83756a86e
    md5: 28a9b9fb585e83a6afc77104074831be
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f00bb5ac7223e75d7f5cc4acba0daebc
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_solo.res
  hashes:
    binhash: 1529616607da85356e187690a086af65
    md5: 85f39abd7f0a5f0162e804bd946190e8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 570ab236ff39a402dc037825ad4a67b7
    md5: 162fbaf5f79716c4cf2e9f797d3304b7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9f9941ed9f71adbb777c180daa989ba0
    md5: 7a3610ea66284f41a086f291cb44c260
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_tracer.res
  hashes:
    binhash: ee5c68a378f9f65d3afb0179ff57f0a1
    md5: 54cabff1041b762c2e8ade83a05028a4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c5e978ddc985fca4a568e370cb4bcdbf
    md5: 6eb50c4bfda0ed2c94b1aa71832132f2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1601/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 913c8fc661de6f6a6a8cbd2d20a659a0
    md5: 70961791f3cae3bae6517e2fe067ea53
