format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/atmosphere/restart_dump.astart
  hashes:
    binhash: 5c9427a6f14ebcec2bf754acd26713d8
    md5: d1054afe201a5ff910a33b2ea3f31aea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/atmosphere/um.res.yaml
  hashes:
    binhash: 64ada308e0095c4d1d2f0e70f1e5124e
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/coupler/a2i.nc
  hashes:
    binhash: 7e77cef5b00ede497fcd0f7935c7e2bf
    md5: d1e05920b46ebdb063a638b33ff35aa2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/coupler/i2a.nc
  hashes:
    binhash: 0a01ed6fda8f2234fc0f7f18916b8c27
    md5: 6f251132337d9089b89cc621ea5c7eb7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/coupler/o2i.nc
  hashes:
    binhash: c09afda141b9391906f38eb77e6ba13e
    md5: ed9027411375f52e869068b5f3501af3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/cice_in.nml
  hashes:
    binhash: 35fe8f2b091fc6639618e64653f316a1
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/ice.restart_file
  hashes:
    binhash: 7f5683ef6c246cea89616bab29e9eae0
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.14481101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14481101
  hashes:
    binhash: b6af6791b3d159412c24ed3dbc4df504
    md5: 25a2112359413e5169c32f4d2d9363cb
work/ice/RESTART/iced.14481201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14481201
  hashes:
    binhash: f394828fa013928e305e061b4755c980
    md5: 01c52677219bab6ac315720a08f56626
work/ice/RESTART/iced.14490101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490101
  hashes:
    binhash: 5dc65699235f914670fa479f073bbf01
    md5: caf6461646c6863ce065d220381bd870
work/ice/RESTART/iced.14490201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490201
  hashes:
    binhash: 2c49a301d8007df98ce5b417974cce3e
    md5: e2139e9e71a81ab321f80d18da0a000c
work/ice/RESTART/iced.14490301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490301
  hashes:
    binhash: dcf3b094a11f96718d7c6aa2b917bc5a
    md5: 540da845ab35e6643c66c44840940c10
work/ice/RESTART/iced.14490401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490401
  hashes:
    binhash: 1b9da9a3e6e13a49013ca16364e0e510
    md5: e34c2937c8309e7d64804b414c11cb52
work/ice/RESTART/iced.14490501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490501
  hashes:
    binhash: 2777c45df73e51610ed3c367640546dd
    md5: b1b8e34051b90a6a9836028d6c362c7b
work/ice/RESTART/iced.14490601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490601
  hashes:
    binhash: 0fa4fba96840f3d48f2d5e0382fa2e2b
    md5: cd91f6bc95c335b75f22aa66f0c8619e
work/ice/RESTART/iced.14490701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490701
  hashes:
    binhash: bf916b384ea4b11f31c15447f8c48a3c
    md5: ec34b7ba2251c4b00e882f33816c1d8d
work/ice/RESTART/iced.14490801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490801
  hashes:
    binhash: 5159d4776d3163ee85d2b3b9242094f1
    md5: 27739a585d5f7abaa8230258fe3fe10e
work/ice/RESTART/iced.14490901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14490901
  hashes:
    binhash: b9280f8d913f14ac068e154ec0ba44f2
    md5: 642b1141b0f9df3a0251b34ac369b77f
work/ice/RESTART/iced.14491001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/iced.14491001
  hashes:
    binhash: da057991aa9d3fd79843dbf33e02204b
    md5: c483186bc506c26759daa7519636aa3a
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/input_ice.nml
  hashes:
    binhash: 433f8ca906be3eee6d8293595ad341fb
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/mice.nc
  hashes:
    binhash: e07ef93aff586e3c65428d979ae6a3c5
    md5: 7f91b79274c0829c68593fd0271656fb
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ice/reset.iced.850
  hashes:
    binhash: 415c7c7ba8253507c55f621edd6d5f7d
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 3e71bc5bfa9b47bb8ad04ebac0d823fa
    md5: 108e841d0076cca730ae707db86d6efe
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: deb50aac0b688fd0bf83da99c7bc6142
    md5: fddd46898781473e4593d0b6c2808755
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_age.res.nc
  hashes:
    binhash: ddbd6799eecd5a970eea494ac8ff6217
    md5: 11796886feb08acc695f5e2036b2dd35
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 698003ad103e57b2dc876d26d9352f16
    md5: cfa1cd157980e7c2da40c071e1cc9f89
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 50fbfbdd86975e42630b32d7d4393270
    md5: 08b39f0f6e5d4c61cf55c259f3636dbd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_density.res.nc
  hashes:
    binhash: b7b0f37252018aae063392cffe973d95
    md5: 7db8faad70582d00abebd6ee78df9e1f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c575afc88e667126097660d05828e496
    md5: ed115a75244b28c38ebc9461187d97af
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e60edb256937ce4f9f32507dc2cae140
    md5: ba89094393307a613252fe06c852d6c8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ae4d8ebceb763fb5f443b51166095ba3
    md5: 4799cb7b9ea165296f33683868f2493c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ccb55775b85eceb14f8b137f3a289fea
    md5: b196f183bb9d77469f40a2e772efe7e7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2adb651c6ab7ce7ac0fa32fd026e6558
    md5: 2f9020a85376062f41bcc663e0e209a2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b3c8018912501c888fcd68055c33120f
    md5: 9dc480316d10000c4e5c5bf7c938bc62
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_solo.res
  hashes:
    binhash: 00cc5956de65d1392354ca0abd7688ba
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b9219d59850b87afb4311bc29ce1f88d
    md5: 6d14bfaade748a22da3dfc59e9b6ac74
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ead96ff1ccf6693d71e4880c263307e3
    md5: 21b2a2ff8ff1fae043558fa714f8eb31
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_tracer.res
  hashes:
    binhash: 1399ad80b19262f744c447f4bd89778a
    md5: 3d106362e4f866d1bfcb869fe5923540
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7c85077a0850fd9695c3d2097b73c246
    md5: 0b7886c593672d404fc4d7ce16537ffa
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart061/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 27d855e34b52acc711815c576fb66fe7
    md5: 659a39ceec825f669295b380d037f2d8
